services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ql_bd
      POSTGRES_USER: root
      POSTGRES_PASSWORD: KngtXmcdR0+bP2O+XxUGTA==
    ports:
      - "9219:5432"
    volumes:
      - ./postgres/data:/data/db
    restart: always

  # redis:
  #   image: redis:7-alpine
  #   container_name: nestjs-redis
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   networks:
  #     - app-network
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
