export const EntityTable = {
  USER: 'user',
  AUTH: 'auth',
  AUTH_PROVIDER: 'auth_provider',
  AUTH_SESSION: 'auth_session',
  NOTIFICATION: 'notification',
  MAIL_CONFIG: 'mail_config',
  TENDER_SESSION: 'phien_dau_thau',
  TENDER_CRITERIA: 'tieu_chi_dau_thau',
  TENDER_SUBMISSION: 'de_xuat_dau_thau',
  TENDER_SUBMISSION_VALUE: 'gia_tri_de_xuat',
  AUCTION_SESSION: 'phien_dau_gia',
  AUCTION_BID: 'gia_dau_gia',
  AUDIT_LOG: 'nhat_ky_kiem_toan',
} as const;
