export const EntityTable = {
  USER: 'user',
  AUTH: 'auth',
  AUTH_PROVIDER: 'auth_provider',
  AUTH_SESSION: 'auth_session',
  NOTIFICATION: 'notification',
  MAIL_CONFIG: 'mail_config',
  TENDER_SESSION: 'phien_dau_thau',
  TENDER_CRITERIA: 'tieu_chi_dau_thau',
  TENDER_SUBMISSION: 'de_xuat_dau_thau',
  TENDER_SUBMISSION_VALUE: 'gia_tri_de_xuat',
  AUCTION_SESSION: 'phien_dau_gia',
  AUCTION_BID: 'gia_dau_gia',
  AUDIT_LOG: 'nhat_ky_kiem_toan',
  DON_VI_HANH_CHINH: 'don_vi_hanh_chinh',
  TO_CHUC_PROFILE: 'to_chuc_profiles',
  XAC_MINH_USER: 'xac_minh_users',
  LOAI_DANH_MUC: 'loai_danh_mucs',
  DANH_MUC: 'danh_mucs',
  THONG_KE: 'thong_kes',
  BAO_CAO_USER: 'bao_cao_users',
} as const;
