export const EntityTable = {
  USER: 'user',
  AUTH: 'auth',
  STUDENT_PROFILE: 'student_profile',
  TUTOR_PROFILE: 'tutor_profile',
  NOTIFICATION: 'notification',
  CLASS: 'class',
  WALLET: 'wallet',
  WALLET_TRANSACTION: 'wallet_transaction',
  PAYMENT: 'payment',
  SERVICE: 'service',
  SERVICE_ORDER: 'service_order',
  REVIEW: 'review',
  BID: 'bid',
  ENROLLMENT: 'enrollment',
  DEPOSIT_PACKAGE: 'deposit_package',
  REPORT: 'report',
  MAIL_CONFIG: 'mail_config',
} as const;
